# Generated by Django 5.2 on 2025-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_done_task_created_at_task_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
