# Generated by Django 5.2 on 2025-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='degree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
