# Generated by Django 5.2 on 2025-05-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_position'),
        ('tasks', '0006_alter_taskcomment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
