# Generated by Django 5.2 on 2025-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='started',
            new_name='received',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
