# Generated by Django 5.2 on 2025-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_started_task_received_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('assigned', 'Topshiriq berildi'), ('accepted', 'Qabul qilindi'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Bajarildi'), ('approved', 'Tasdiqlandi'), ('expired', 'Bajarilmadi'), ('returned', 'Qayta ishlashga yuborildi')], max_length=50),
        ),
    ]
