# Generated by Django 5.2 on 2025-05-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='degree',
            field=models.CharField(choices=[('info', "Ma'lumot uchun"), ('medium', "O'rtacha"), ('important', 'Muhim'), ('very_important', 'Juda muhim'), ('urgent', 'Tezkor')], default='medium', max_length=50),
        ),
    ]
