# Generated by Django 5.2 on 2025-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
