# Generated by Django 5.2 on 2025-05-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
