# Generated by Django 5.2 on 2025-05-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('assigner', 'Buyuruvchi'), ('performer', 'Ijrochi'), ('dual', 'Buyuruvchi hamda ijrochi')], max_length=50),
        ),
    ]
